steps:
  # 構建 Docker 鏡像
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-frontend:$COMMIT_SHA",
        "-f",
        "apps/frontend/Dockerfile",
        ".",
        "--build-arg",
        "NEXT_PUBLIC_API_URL=${_BACKEND_URL}",
        "--build-arg",
        "NEXT_PUBLIC_BASE_URL=${_FRONTEND_URL}",
        "--build-arg",
        "NEXTAUTH_URL=${_NEXTAUTH_URL}",
        "--build-arg",
        "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}",
      ]
  # 推送 Docker 鏡像
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-frontend:$COMMIT_SHA",
      ]

  # 部署到 Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-frontend:$COMMIT_SHA"
      - "--region=asia-east1"
      - "--platform=managed"
      - "--allow-unauthenticated"

# 替換變數
substitutions:
  _BACKEND_URL: "https://oms-backend-url.run.app" # 將在 Cloud Build 觸發器中設置為後端服務的 URL
  _FRONTEND_URL: "https://oms-frontend-url.run.app" # 將在 Cloud Build 觸發器中設置為前端服務的 URL
  _NEXTAUTH_URL: "https://oms-nextauth-url.run.app" # 將在 Cloud Build 觸發器中設置為 NextAuth 服務的 URL
  _NEXTAUTH_SECRET: "nextauth-secret" # 將在 Cloud Build 觸發器中設置為 NextAuth 密鑰
  _SERVICE_NAME: "oms-frontend-service"

# 構建的鏡像
images:
  - "asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-frontend:$COMMIT_SHA"

# 超時設置
timeout: "1800s"

# 日誌設置 - 解決服務帳號錯誤
options:
  logging: CLOUD_LOGGING_ONLY
