# cloudbuild.backend.yaml
steps:
  # 步驟 1: 建構 Docker 映像
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-backend:$COMMIT_SHA" # 映像名稱和標籤
      - "-f"
      - "apps/backend/Dockerfile" # 指定 Dockerfile 路徑
      - "." # Docker Build Context 為 monorepo 根目錄 (非常重要)
  # 步驟 2: 推送 Docker 映像到 Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-backend:$COMMIT_SHA",
      ]
  - name: "node:18-alpine" # 或其他你使用的 Node.js 映像
    entrypoint: sh
    args:
      - "-c"
      - |
        apk add --no-cache postgresql-client openssl

        # 設定 DATABASE_URL 環境變數
        export DATABASE_URL="postgresql://${_DB_USER}:${_DB_PASSWORD}@${_DB_HOST}:5432/oms"

        # 確保 pnpm 在這個映像中可用，如果 node:18-alpine 沒有預裝 pnpm
        npm install -g pnpm

        # 複製 monorepo 的程式碼和 node_modules/.pnpm 到此步驟的容器中
        # 從 Cloud Build 的原始工作目錄複製（假設是 monorepo 根目錄）
        cp -R . /tmp/monorepo

        # 進入 prisma-client 專案的目錄，或者 backend 應用程式目錄（如果 schema 在 backend 中）
        # 這裡假設你的 schema.prisma 在 packages/prisma-client/prisma
        cd /tmp/monorepo/packages/prisma-client

        # 執行 Prisma Migrate Deploy
        # 由於我們只複製了生產依賴，可能需要確保 pnpm install 再次執行以確保 prisma CLI 可用
        # 但更優雅的方式是確保 pnpm 的 global install 指向了 prisma CLI
        # 假設 pnpm install --frozen-lockfile 已經在 builder 階段完整執行，
        # 並且相關的 bin 連結在 .pnpm 下是可用的，則可以直接使用 `pnpm prisma`。
        # 如果遇到 "command not found"，則需要先執行 pnpm install。
        # 為了保險起見，我們可以在此階段重新安裝依賴以確保 `prisma` CLI 可用
        pnpm install --frozen-lockfile # 重新安裝生產依賴，確保 Prisma CLI 可用
        pnpm db:migrate
    env:
      - "DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@${_DB_HOST}:5432/oms"
    id: "Run Prisma Migrations"

  # 步驟 3: 部署到 Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "oms-backend-service" # Cloud Run 服務名稱
      - "--image"
      - "asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-backend:$COMMIT_SHA"
      - "--region"
      - "asia-east1" # 替換為你的 GCP 區域 (例如 asia-east1, us-central1)
      - "--platform"
      - "managed"
      - "--allow-unauthenticated" # 如果是公開 API，允許未經驗證的存取 (可根據需求調整)
      - "--set-env-vars" # 設定環境變數
      - "DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@/oms?host=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME}"
      - "--add-cloudsql-instances"
      - "${_CLOUD_SQL_CONNECTION_NAME}"
    # 其他可選配置：
    # - '--cpu' # CPU 配置 (例如: 1 或 2)
    # - '1'
    # - '--memory' # 記憶體配置 (例如: 512Mi, 1Gi)
    # - '512Mi'
    # - '--min-instances' # 最小執行個體數 (防止冷啟動，會產生費用)
    # - '0' # 0 表示按需啟動
    # - '--max-instances' # 最大執行個體數
    # - '10'
    # - '--timeout' # 請求超時時間 (例如: 300s)
    # - '300'
images:
  - "asia-east1-docker.pkg.dev/$PROJECT_ID/oms/oms-backend:$COMMIT_SHA"

# 替換變數，用於敏感資訊或環境特定配置
substitutions:
  _DB_HOST: "localhost"
  _DB_USER: "prisma_user"
  _DB_PASSWORD: "your_actual_database_password"
  _CLOUD_SQL_CONNECTION_NAME: "your_actual_database_connection_string_here" # <-- 在 Cloud Build Trigger 中設定

options:
  logging: CLOUD_LOGGING_ONLY
