# Docker Compose 配置

services:
  # PostgreSQL 資料庫
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: oms
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin 4 服務
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # 後端服務
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3003:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/oms
      - JWT_SECRET=local_development_secret
      - NODE_ENV=development
    depends_on:
      - db

volumes:
  postgres_data:
