# Docker Compose 配置

services:
  # PostgreSQL 資料庫
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: oms
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin 4 服務
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # 後端服務
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3003:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/oms
      - JWT_SECRET=local_development_secret
      - NODE_ENV=development
      - PRISMA_SCHEMA_PATH=/app/packages/prisma-client/prisma/schema.prisma
      - PRISMA_GENERATE_DATAPROXY=false
    depends_on:
      - db
      
  # 前端服務
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001/api
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_SKIP_TYPE_CHECK=1
    depends_on:
      - backend

volumes:
  postgres_data:
