steps:
  # 構建 Docker 鏡像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oms-backend:$COMMIT_SHA', '-f', 'apps/backend/Dockerfile', '.']

  # 推送鏡像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oms-backend:$COMMIT_SHA']

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'oms-backend'
      - '--image=gcr.io/$PROJECT_ID/oms-backend:$COMMIT_SHA'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=treerful-200611:asia-east1:oms'
      - '--set-env-vars=DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@localhost:5432/oms?host=/cloudsql/treerful-200611:asia-east1:oms,JWT_SECRET=${_JWT_SECRET}'

# 替換變數
substitutions:
  _DB_PASSWORD: '' # 將在 Cloud Build 觸發器中設置
  _JWT_SECRET: '' # 將在 Cloud Build 觸發器中設置

# 構建的鏡像
images:
  - 'gcr.io/$PROJECT_ID/oms-backend:$COMMIT_SHA'

# 超時設置
timeout: '1800s'

# 日誌設置 - 解決服務帳號錯誤
options:
  logging: CLOUD_LOGGING_ONLY
